on: 
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to build'     
        required: true
        type: choice
        options:
        - docker
env:
  FILE_PATH: ${{ github.event.inputs.image }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets. DOCKER_PASSWORD }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0
    
    - name: Build and push docker image to DockerHub
      run: | 
        VERSION=$(git describe --always --abbrev=0 --match "NOT A TAG")
        VERSION_READABLE=$(git describe --tag)
        cd $FILE_PATH
        docker build --platform "linux/amd64" --build-arg VERSION="$VERSION" --build-arg VERSION_READABLE="$VERSION_READABLE" -t accern/docker-image:$VERSION_READABLE .
